results_UD_accuracy = featureAnalysisSingleData(UD_accuracy_data)
print(results_UD_accuracy)

results_UD_speed = featureAnalysisSingleData(UD_speed_data)
print(results_UD_speed)

results_UD_keyPreference = featureAnalysisSingleData(UD_keyPreference_data)
print(results_UD_keyPreference)

results_UD_reaction = featureAnalysisSingleData(UD_reaction_data)
print(results_UD_reaction)